# Generated by Django 4.1.4 on 2022-12-16 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_company_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='images')),
                ('product_price', models.IntegerField()),
                ('enterd_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_specialisation', models.CharField(choices=[('chest', 'Chest'), ('heart', 'Heart'), ('general', 'General'), ('orthopadeic', 'Orthopadeic')], default='general', max_length=50)),
                ('doctor_number', models.IntegerField()),
                ('doctor_location', models.CharField(max_length=50)),
                ('enterd_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
