# Generated by Django 4.1.4 on 2023-01-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('date_appointment', models.DateField()),
                ('time_appointment', models.TimeField()),
                ('enterd_by', models.CharField(max_length=255)),
            ],
        ),
    ]
