# Generated by Django 4.1.4 on 2023-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_doctorappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='date_appointment',
            field=models.DateField(verbose_name=['%m-%d-%Y']),
        ),
    ]
