# Generated by Django 4.1.4 on 2023-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_doctorappointment_date_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='date_appointment',
            field=models.DateField(),
        ),
    ]
