# Generated by Django 4.1.4 on 2023-01-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_doctorappointment_date_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity_ordered', models.IntegerField()),
                ('enterd_by', models.CharField(max_length=255)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.adddoctor')),
            ],
        ),
    ]
