# Generated by Django 4.1.4 on 2023-01-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_alter_dealsdetails_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddoctor',
            name='enterd_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='enterd_by',
            field=models.CharField(max_length=255),
        ),
    ]
